// Deterministic mock provider: scores and text are derived from a seed
// (researcher name + provider id) so runs are reproducible without API keys.

import { createHash } from "node:crypto";
import type { AnalysisOutput } from "../schema";
import { CRITERIA, SECTION_TITLES } from "../schema";
import type { LlmProvider } from "./types";

/** mulberry32 PRNG seeded from a string. */
export function seededRandom(seed: string): () => number {
  const hash = createHash("sha256").update(seed).digest();
  let a = hash.readUInt32LE(0);
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Pull "Name: …", "Field: …" and the publication list back out of the user message. */
export function parseUserMessage(user: string): { name: string; field: string; titles: string[] } {
  const name = user.match(/^Name:\s*(.+)$/m)?.[1]?.trim() ?? "The researcher";
  const field = user.match(/^Field:\s*(.+)$/m)?.[1]?.trim() ?? "their field";
  const titles = [...user.matchAll(/^\[(\d+)\]\s+(.+?)\s+\(\d{4}/gm)].map((m) => m[2]);
  return { name, field, titles };
}

const ADJECTIVES = ["thorough", "careful", "ambitious", "incremental", "well-documented", "uneven", "methodical", "exploratory"];

export function generateMockOutput(seed: string, user: string): AnalysisOutput {
  const rnd = seededRandom(seed);
  const { name, field, titles } = parseUserMessage(user);
  const base = 45 + Math.floor(rnd() * 40); // 45–84
  const scores = Object.fromEntries(
    CRITERIA.map((c) => [c, Math.max(0, Math.min(100, base + Math.floor(rnd() * 25) - 12))]),
  ) as AnalysisOutput["scores"];
  const pick = () => ADJECTIVES[Math.floor(rnd() * ADJECTIVES.length)];
  const cite = (i: number) => `[${((i + Math.floor(rnd() * Math.max(1, titles.length))) % Math.max(1, titles.length)) + 1}]`;
  const surname = name.split(/\s+/).pop() ?? name;
  const n = titles.length;

  const rationale = Object.fromEntries(
    CRITERIA.map((c) => [
      c,
      `${c[0].toUpperCase()}${c.slice(1)} is ${pick()} across the ${n} listed works; ${cite(0)} and ${cite(1)} are the clearest examples, while ${cite(2)} is weaker on this point.`,
    ]),
  ) as AnalysisOutput["rationale"];

  const summary =
    `${name} is a researcher in ${field.toLowerCase()} whose output over ${n} indexed publications centres on ${titles[0] ? `work such as "${titles[0]}" ${cite(0)}` : "a compact body of work"}. ` +
    `The programme is ${pick()} in design and ${pick()} in execution, with the most cited contributions ${cite(0)} and ${cite(1)} setting the direction for later studies.\n\n` +
    `Judged by the standards of ${field.toLowerCase()}, ${surname}'s work is ${pick()}: methods are ${scores.rigor >= 65 ? "generally sound" : "sometimes under-specified"}, ` +
    `artefacts are ${scores.reproducibility >= 65 ? "largely available" : "only partially available"}, and the influence of ${cite(2)} on subsequent work is ${scores.impact >= 65 ? "clear" : "still limited"}.`;

  const sections = SECTION_TITLES.map((title, i) => ({
    title,
    body:
      `${title} in ${surname}'s publications is ${pick()}. ${cite(i)} illustrates the typical approach, while ${cite(i + 1)} shows the main limitation.\n\n` +
      `A ${pick()} reading of ${cite(i + 2)} suggests the pattern holds across the period covered by the list. This assessment was generated by the mock provider "${seed.split("::")[1] ?? "mock"}" for development purposes.`,
  }));

  const publicationScores = titles.map(() => Math.max(0, Math.min(100, base + Math.floor(rnd() * 30) - 15)));
  const benchmarkAdjective = pick();

  return {
    scores,
    rationale,
    summary,
    sections,
    strengths: [`Consistent focus ${cite(0)}`, `Clear reporting in ${cite(1)}`, `${benchmarkAdjective[0].toUpperCase()}${benchmarkAdjective.slice(1)} benchmarks`],
    concerns: [`Limited independent replication of ${cite(2)}`, `Some artefacts not released`],
    publicationScores,
  };
}

export function createMockProvider(id = "mock"): LlmProvider {
  return {
    id,
    async complete(_system, user) {
      const { name } = parseUserMessage(user);
      const output = generateMockOutput(`${name}::${id}`, user);
      // Wrapped in a code fence on purpose: exercises the fence stripping in the parser.
      return "```json\n" + JSON.stringify(output, null, 2) + "\n```";
    },
  };
}
