import Link from "next/link";

const links = [
  { href: "#", label: "About" },
  { href: "#", label: "Methodology" },
  { href: "/api/researchers", label: "API" },
  { href: "#", label: "Privacy" },
  { href: "#", label: "GitHub" },
];

export function Footer() {
  return (
    <footer className="mt-16 border-t border-border">
      <div className="site-container flex flex-wrap items-center justify-between gap-x-6 gap-y-3 py-6 text-[13px] text-muted">
        <p className="max-w-[640px]">
          Analyses are generated by language models and can contain errors · Content available under an open license
        </p>
        <nav className="flex flex-wrap gap-x-5 gap-y-2" aria-label="Footer">
          {links.map((l) => (
            <Link key={l.label} href={l.href} className="hover:text-ink">
              {l.label}
            </Link>
          ))}
        </nav>
      </div>
    </footer>
  );
}
